--Create Raw Table
CREATE TABLE superstore_raw (
    row_id INT,
    order_id VARCHAR(30),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(50),
    customer_id VARCHAR(20),
    customer_name VARCHAR(100),
    segment VARCHAR(50),
    country VARCHAR(50),
    city VARCHAR(50),
    state VARCHAR(50),
    postal_code INT,
    region VARCHAR(50),
    product_id VARCHAR(30),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(255),
    sales DECIMAL(10,2),
    quantity INT,
    discount DECIMAL(5,2),
    profit DECIMAL(10,4)
);
--Import the CSV into superstore_raw using Table Data Import Wizard.


--2. Create Customers Table
CREATE TABLE customers (
    customer_id VARCHAR(20) PRIMARY KEY,
    customer_name VARCHAR(100),
    segment VARCHAR(50),
    country VARCHAR(50),
    city VARCHAR(50),
    state VARCHAR(50),
    postal_code INT,
    region VARCHAR(50)
);
--Insert Data:
INSERT INTO customers
SELECT DISTINCT
    customer_id,
    customer_name,
    segment,
    country,
    city,
    state,
    postal_code,
    region
FROM superstore_raw;


--3. Create Products Table
CREATE TABLE products (
    product_id VARCHAR(30) PRIMARY KEY,
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(255)
);
--Insert Data:
INSERT INTO products
SELECT DISTINCT
    product_id,
    category,
    sub_category,
    product_name
FROM superstore_raw;


--4. Create Orders Table
CREATE TABLE orders (
    row_id INT PRIMARY KEY,
    order_id VARCHAR(30),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(50),
    customer_id VARCHAR(20),
    product_id VARCHAR(30),
    sales DECIMAL(10,2),
    quantity INT,
    discount DECIMAL(5,2),
    profit DECIMAL(10,4)
);
--Insert Data:
INSERT INTO orders
SELECT
    row_id,
    order_id,
    order_date,
    ship_date,
    ship_mode,
    customer_id,
    product_id,
    sales,
    quantity,
    discount,
    profit
FROM superstore_raw;


--5. Subquery – Orders Above Average Sales
SELECT *
FROM orders
WHERE sales >
(
    SELECT AVG(sales)
    FROM orders
);
--Insight
--Orders returned by this query have sales greater than the overall average sales.


--6. Subquery – Highest Order Per Customer
SELECT *
FROM orders o
WHERE sales =
(
    SELECT MAX(sales)
    FROM orders
    WHERE customer_id = o.customer_id
);
--Insight
--Shows each customer's highest-value order.


--7. CTETotal Sales Per Customer
WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)
SELECT *
FROM customer_sales
ORDER BY total_sales DESC;
--Insight
--Calculates total revenue generated by each customer.


--8. Window Function  ROW_NUMBER()
SELECT
    customer_id,
    sales,
    ROW_NUMBER() OVER
    (
        PARTITION BY customer_id
        ORDER BY sales DESC
    ) AS row_num
FROM orders;
--Insight
--Assigns a unique sequence number to each customer's orders.


--9. Window Function – RANK()
SELECT
    customer_id,
    SUM(sales) AS total_sales,
    RANK() OVER
    (
        ORDER BY SUM(sales) DESC
    ) AS sales_rank
FROM orders
GROUP BY customer_id;
--Insight
--Ranks customers according to total sales.


--10. JOIN + CTE + Window Function
WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)

SELECT
    c.customer_id,
    c.customer_name,
    cs.total_sales,
    RANK() OVER
    (
        ORDER BY cs.total_sales DESC
    ) AS customer_rank
FROM customer_sales cs
JOIN customers c
ON cs.customer_id = c.customer_id;
--Insight
--Displays customer name, total sales, and rank together.


--11. Top 10 Customers
WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)

SELECT *
FROM customer_sales
ORDER BY total_sales DESC
LIMIT 10;
--Insight
--Identifies the most valuable customers.


--12. Lowest 10 Customers
WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)

SELECT *
FROM customer_sales
ORDER BY total_sales ASC
LIMIT 10;
--Insight
--Shows customers contributing the least sales.


--13. Single-Order Customers
SELECT
    customer_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(DISTINCT order_id) = 1;
--Insight
--These customers have placed only one order.


--14. Customers with Above-Average Total Sales
WITH customer_sales AS
(
    SELECT
        customer_id,
        SUM(sales) AS total_sales
    FROM orders
    GROUP BY customer_id
)

SELECT *
FROM customer_sales
WHERE total_sales >
(
    SELECT AVG(total_sales)
    FROM customer_sales
);
--Insight
--These customers generate more sales than the average customer.